[package]
name = "fast-tcp-vpn"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fast-tcp-vpn"
path = "src/main.rs"

[dependencies]
tun = "0.6"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"

