[package]
name = "fast-tcp-vpn"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fast-tcp-vpn"
path = "src/main.rs"

[dependencies]
tun = { version = "0.7", features = ["async"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
etherparse = "0.18"
libc = "0.2"
scopeguard = "1"
