[client]
server_addr = "38.175.192.236:9000"
auto_reconnect = true
reconnect_delay_secs = 5

[network]
mtu = 1400

[tunnel]
name = "tun0"
address = "10.0.0.2"
prefix_len = 24

[security]
psk = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
